# Sea Turtle Stranding Analysis Configuration

# Input/Output file paths
files:
  projects: "data/project_summary_export_1_3_2025.xlsx"
  turtles: "data/20250204_USACE_STSSN_report.xlsx"
  output: "output/updated_STSSN_report.xlsx"

# Analysis parameters
analysis:
  # Multiple distance thresholds in kilometers
  distance_thresholds: [5, 10, 15]

# Performance settings
performance:
  use_spatial_index: true
  use_parallel: true
  batch_size: 1000